/**
 * Bulk insert HK schools into Supabase
 */
import { createClient } from "@supabase/supabase-js";

const ANON_KEY = "sb_publishable_D1Wc8MSqizR6dsPrPNimdw_gAX-ZVkr";
const supabase = createClient("https://jypwqezctpidgiqqolaq.supabase.co", ANON_KEY);

const schools = [
  // HK Island
  { name: "英皇書院", name_en: "King's College", address: "中西區荷李活道75號", phone: "2540 3101", district: "中西區", level: "中學", type: "官立", gender: "男", band: "Band 1", established: 1862, teaching_lang: "英文", features: ["游泳","田徑","STEM"], description: "歷史悠久官立男校，HKDSE成績出眾。", student_count: 850, parent_rating: 4.6 },
  { name: "聖士提反堂中學", name_en: "St. Stephen's Girls' College", address: "中西區堅道26號", phone: "2522 5139", district: "中西區", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1906, teaching_lang: "英文", features: ["音樂","舞蹈","戲劇","田徑"], description: "傳統名校，學術及非學術表現均出類拔萃。", student_count: 750, parent_rating: 4.7 },
  { name: "華仁書院", name_en: "Wah Yan College", address: "灣仔皇后大道東281號", phone: "2572 5227", district: "灣仔", level: "中學", type: "資助", gender: "男", band: "Band 1", established: 1919, teaching_lang: "英文", features: ["戲劇","足球","籃球","辯論"], description: "耶穌會辦學，傳統名校，着重全人教育。", student_count: 900, parent_rating: 4.8 },
  { name: "香港真光中學", name_en: "True Light Middle School of Hong Kong", address: "灣仔跑馬地黃泥涌道51號", phone: "2575 5923", district: "灣仔", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["音樂","舞蹈","田徑","游泳"], description: "真光旗下名牌女校，着重女性領導力培養。", student_count: 820, parent_rating: 4.7 },
  { name: "聖保祿中學", name_en: "St. Paul's Convent School", address: "灣仔皇后大道東57號", phone: "2528 8131", district: "灣仔", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1854, teaching_lang: "英文", features: ["音樂","戲劇","田徑","合唱"], description: "香港歷史最悠久的女校之一，校風純樸。", student_count: 800, parent_rating: 4.6 },
  { name: "張祝珊英文中學", name_en: "Cheung Chuk Shan College", address: "北角琴紡街1號", phone: "2568 0661", district: "東區", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1965, teaching_lang: "英文", features: ["田徑","游泳","舞蹈","STEM"], description: "英語教學，着重全人教育，校風良好。", student_count: 780, parent_rating: 4.6 },
  { name: "金文泰中學", name_en: "Clementi Secondary School", address: "北角炮台山道30號", phone: "2577 8171", district: "東區", level: "中學", type: "官立", gender: "男", band: "Band 1", established: 1926, teaching_lang: "英文", features: ["足球","田徑","游泳","STEM"], description: "香港最歷史悠久官中之一，學術成績出眾。", student_count: 880, parent_rating: 4.6 },
  { name: "聖類斯中學", name_en: "St. Louis School", address: "北角雲景道20號", phone: "2563 0172", district: "東區", level: "中學", type: "資助", gender: "男", band: "Band 1", established: 1926, teaching_lang: "英文", features: ["足球","田徑","游泳","籃球"], description: "北角著名男校，天主教背景，校風純樸。", student_count: 850, parent_rating: 4.5 },
  { name: "瑪利曼中學", name_en: "Marymount Secondary School", address: "北角藍塘道61號A", phone: "2575 2918", district: "東區", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["音樂","舞蹈","網球","游泳"], description: "傳統名牌女校，一條龍升學，着重女性領袖培養。", student_count: 750, parent_rating: 4.8 },
  { name: "嘉諾撒聖方濟各書院", name_en: "St. Francis' Canossian College", address: "北角柏麗大道2號", phone: "2566 2771", district: "東區", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1860, teaching_lang: "英文", features: ["音樂","舞蹈","田徑","網球"], description: "嘉諾撒旗下頂級女校，學術及藝術表現傑出。", student_count: 720, parent_rating: 4.7 },
  { name: "衞理中學", name_en: "Methodist College", address: "北角炮台山道31號", phone: "2577 0261", district: "東區", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1937, teaching_lang: "英文", features: ["田徑","游泳","合唱","足球"], description: "循道衞理著名中學，一條龍小學+中學。", student_count: 900, parent_rating: 4.6 },
  { name: "聖公會鄧肇堅中學", name_en: "SKH Tang Shiu Kin Secondary School", address: "北角電氣道218號", phone: "2562 0771", district: "東區", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1967, teaching_lang: "英文", features: ["足球","田徑","舞蹈","合唱"], description: "聖公會屬校，着重多元智能發展。", student_count: 880, parent_rating: 4.4 },
  { name: "中華基金中學", name_en: "China基金 Secondary School", address: "柴灣怡盛街11號", phone: "2555 7661", district: "東區", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1956, teaching_lang: "英文", features: ["足球","田徑","合唱","STEM"], description: "柴灣區老牌中學，着重基督教全人教育。", student_count: 820, parent_rating: 4.3 },
  { name: "聖士提反書院", name_en: "St. Stephen's College", address: "南區大潭紅山道18號", phone: "2552 2341", district: "南區", level: "中學", type: "資助", gender: "男", band: "Band 1", established: 1903, teaching_lang: "英文", features: ["游泳","帆船","足球","戲劇"], description: "南區頂級男校，逾120年歷史，全寄宿學校。", student_count: 750, parent_rating: 4.8 },
  { name: "香港仔工業學校", name_en: "Aberdeen Technical School", address: "南區香港仔水塘道15號", phone: "2552 4121", district: "南區", level: "中學", type: "資助", gender: "男", band: "Band 2", established: 1935, teaching_lang: "英文", features: ["足球","田徑","機械工程"], description: "南區老牌工業中學，着重技能培訓。", student_count: 700, parent_rating: 4.0 },
  // Kowloon
  { name: "協恩中學", name_en: "Heep Yunn School", address: "九龍城農圃道1號", phone: "2382 0211", district: "九龍城", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["田徑","游泳","舞蹈","合唱","STEM"], description: "九龍城區頂級女校，一條龍中學，學術及體育表現出眾。", student_count: 820, parent_rating: 4.8 },
  { name: "瑪利諾書院", name_en: "Maryknoll Secondary School", address: "九龍城窩打老道72號", phone: "2383 0101", district: "九龍城", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1921, teaching_lang: "英文", features: ["田徑","游泳","合唱","戲劇"], description: "九龍城區頂級女校，天主教背景，學術及藝術表現出眾。", student_count: 800, parent_rating: 4.7 },
  { name: "華仁書院 (九龍)", name_en: "Wah Yan College, Kowloon", address: "九龍城窩打老道54號", phone: "2382 0101", district: "九龍城", level: "中學", type: "資助", gender: "男", band: "Band 1", established: 1924, teaching_lang: "英文", features: ["足球","籃球","田徑","合唱","辯論"], description: "耶穌會辦學，九龍城區頂級男校，全人教育。", student_count: 880, parent_rating: 4.7 },
  { name: "真光女書院", name_en: "True Light Girls' College", address: "九龍城窩打老道76號", phone: "2761 5491", district: "九龍城", level: "中學", type: "資助", gender: "女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["田徑","游泳","舞蹈","合唱"], description: "九龍城區著名女校，着重女性領袖培養。", student_count: 780, parent_rating: 4.6 },
  { name: "迦密中學", name_en: "Carmel Secondary School", address: "九龍城窩打老道81號", phone: "2761 5481", district: "九龍城", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1939, teaching_lang: "英文", features: ["田徑","游泳","合唱","足球","STEM"], description: "九龍城區著名中學，基督教背景，學術及體育均衡發展。", student_count: 860, parent_rating: 4.6 },
  { name: "九龍塘學校 (中學部)", name_en: "Kowloon Tong School (Secondary Section)", address: "九龍城窩打老道72號A", phone: "2383 0331", district: "九龍城", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["田徑","游泳","合唱","戲劇"], description: "九龍塘學校一條龍中學部，著名升學名校。", student_count: 800, parent_rating: 4.7 },
  { name: "香港培正中學", name_en: "Pui Ching Middle School", address: "九龍城窩打老道71號", phone: "2761 5471", district: "九龍城", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1933, teaching_lang: "英文", features: ["田徑","游泳","合唱","足球","STEM"], description: "九龍城區著名中學，基督教背景，學術及體育傳統名校。", student_count: 880, parent_rating: 4.7 },
  { name: "聖公會聖三一堂中學", name_en: "SKH Holy Trinity Cathedral College", address: "九龍城嘉林邊道21號", phone: "2382 1701", district: "九龍城", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1956, teaching_lang: "英文", features: ["田徑","游泳","合唱","舞蹈"], description: "九龍城區聖公會中學，學術及非學術均衡發展。", student_count: 820, parent_rating: 4.5 },
  { name: "民生書院", name_en: "Munsang College", address: "九龍城馬莎道16號", phone: "2382 1771", district: "九龍城", level: "中學", type: "直資", gender: "男女", band: "Band 2", established: 1926, teaching_lang: "英文", features: ["田徑","游泳","合唱","戲劇","STEM"], description: "九龍城區老牌直資中學，一條龍小學+中學。", student_count: 900, parent_rating: 4.5 },
  { name: "東華三院黃笏南中學", name_en: "TWGHs Wong Fuk Hwa College", address: "九龍城馬坑涌道18號", phone: "2382 1611", district: "九龍城", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1961, teaching_lang: "英文", features: ["足球","田徑","舞蹈","STEM"], description: "東華三院屬校，着重多元智能發展。", student_count: 840, parent_rating: 4.3 },
  { name: "循道中學", name_en: "Methodist College", address: "旺角洗衣街89號A", phone: "2380 0321", district: "油尖旺", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1951, teaching_lang: "英文", features: ["田徑","游泳","合唱","舞蹈","足球"], description: "循道衞理一條龍中學，學術成績優異。", student_count: 900, parent_rating: 4.7 },
  { name: "九龍工業學校", name_en: "Kowloon Technical School", address: "旺角洗衣街151號", phone: "2380 0551", district: "油尖旺", level: "中學", type: "資助", gender: "男", band: "Band 2", established: 1930, teaching_lang: "英文", features: ["足球","田徑","籃球"], description: "旺角區老牌工業中學，着重技能培訓。", student_count: 780, parent_rating: 4.1 },
  { name: "官立嘉道理爵士中學", name_en: "Sir Ellis Kadoorie College", address: "旺角山東街51號", phone: "2380 0721", district: "油尖旺", level: "中學", type: "官立", gender: "男女", band: "Band 1", established: 1907, teaching_lang: "英文", features: ["田徑","游泳","合唱","辯論"], description: "百年官校，全港首間官立英文中學，學術及音樂傳統出名。", student_count: 860, parent_rating: 4.6 },
  // NT
  { name: "浸會大學附屬學校王錦輝中小學", name_en: "HKBU Affiliated School Wang Fook", address: "沙田銀城街30號", phone: "2691 6888", district: "沙田", level: "中學", type: "直資", gender: "男女", band: "Band 1", established: 2006, teaching_lang: "英文", features: ["游泳","田徑","合唱","STEM","戲劇"], description: "浸會大學附屬直資名校，一條龍中小學，STEM教育見稱。", student_count: 1100, parent_rating: 4.8 },
  { name: "保良局甲寅年總理中學", name_en: "PLK Directors' College", address: "沙田大圍文林路21號", phone: "2694 8688", district: "沙田", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1960, teaching_lang: "英文", features: ["田徑","游泳","舞蹈","合唱","STEM"], description: "保良局旗艦中學，學術及體育均衡發展。", student_count: 880, parent_rating: 4.6 },
  { name: "沙田崇真中學", name_en: "Shatin Tsung Tsin Secondary School", address: "沙田大圍美林邨", phone: "2694 0381", district: "沙田", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1965, teaching_lang: "英文", features: ["田徑","足球","合唱","舞蹈","STEM"], description: "沙田區著名中學，基督教背景，着重大自然教育。", student_count: 860, parent_rating: 4.5 },
  { name: "聖公會曾肇添中學", name_en: "SKH Tsang Shiu Tim Secondary School", address: "沙田沙田圍路36號", phone: "2692 8381", district: "沙田", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1958, teaching_lang: "英文", features: ["田徑","游泳","合唱","足球","STEM"], description: "沙田區老牌名校，聖公會背景，學術及體育均衡。", student_count: 840, parent_rating: 4.6 },
  { name: "浸信會呂明才中學", name_en: "Baptist Lui Ming Choi Secondary School", address: "沙田沙田圍博康邨", phone: "2693 8281", district: "沙田", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1965, teaching_lang: "英文", features: ["田徑","足球","合唱","舞蹈"], description: "沙田區浸信會中學，着重全人教育。", student_count: 820, parent_rating: 4.4 },
  { name: "嗇色園主辦可風中學", name_en: "Ho Fung College", address: "屯門掃管笏青楊路88號", phone: "2458 2888", district: "屯門", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1996, teaching_lang: "英文", features: ["田徑","游泳","合唱","STEM","戲劇"], description: "嗇色園佛教背景，屯門區頂級中學，學術成績出眾。", student_count: 900, parent_rating: 4.7 },
  { name: "順德聯誼總會梁植偉中學", name_en: "STFA Leung Chong Yan School", address: "屯門大興邨", phone: "2467 1288", district: "屯門", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1972, teaching_lang: "英文", features: ["田徑","足球","合唱","STEM"], description: "順德聯誼總會屯門區著名中學，學術及體育均衡。", student_count: 860, parent_rating: 4.5 },
  { name: "順德聯誼總會李兆基中學", name_en: "STFA Lee Shau Kee College", address: "屯門兆康路25號", phone: "2462 0888", district: "屯門", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1978, teaching_lang: "英文", features: ["田徑","足球","合唱","舞蹈"], description: "順德聯誼總會兆康區中學，校風純樸。", student_count: 840, parent_rating: 4.3 },
  { name: "優才書院", name_en: "G.T. (Ellen Yeung) College", address: "將軍澳蓬萊路3號", phone: "2704 6888", district: "將軍澳", level: "中學", type: "直資", gender: "男女", band: "Band 1", established: 2002, teaching_lang: "英文", features: ["合唱","舞蹈","STEM","戲劇","游泳"], description: "將軍澳著名直資一條龍學校，着重創意及多元智能發展。", student_count: 900, parent_rating: 4.7 },
  { name: "播道書院", name_en: "Evangel College", address: "將軍澳學林里8號", phone: "2704 3888", district: "將軍澳", level: "中學", type: "直資", gender: "男女", band: "Band 1", established: 1996, teaching_lang: "英文", features: ["田徑","游泳","合唱","STEM","戲劇"], description: "將軍澳著名直資一條龍學校，學術及體育均衡發展。", student_count: 950, parent_rating: 4.7 },
  { name: "保良局董玉娣中學", name_en: "PLK Tung Yuk Day School", address: "將軍澳常寧路7號", phone: "2704 9888", district: "將軍澳", level: "中學", type: "資助", gender: "男女", band: "Band 1", established: 1960, teaching_lang: "英文", features: ["田徑","足球","合唱","舞蹈","STEM"], description: "保良局將軍澳旗艦中學，着重科技及藝術教育。", student_count: 880, parent_rating: 4.5 },
  { name: "香港道教聯合會鄧顯紀念中學", name_en: "HKTA Tang Hin Memorial Secondary School", address: "上水彩園邨", phone: "2670 6888", district: "北區", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1979, teaching_lang: "英文", features: ["田徑","足球","合唱","道教文化"], description: "北區著名道教背景中學，着重品德教育。", student_count: 840, parent_rating: 4.4 },
  { name: "新界鄉議局元朗區中學", name_en: "NT Heung Yee Kuk Yuen Long District Secondary School", address: "元朗公園南路55號", phone: "2476 8288", district: "元朗", level: "中學", type: "官立", gender: "男女", band: "Band 2", established: 1970, teaching_lang: "英文", features: ["田徑","足球","合唱","舞蹈"], description: "新界鄉議局主辦，元朗區著名官立中學。", student_count: 860, parent_rating: 4.5 },
  { name: "王肇枝中學", name_en: "Wong Shiu Chi Secondary School", address: "大埔安慈路3號", phone: "2656 7188", district: "大埔", level: "中學", type: "資助", gender: "男女", band: "Band 2", established: 1960, teaching_lang: "英文", features: ["田徑","足球","合唱","STEM"], description: "大埔區老牌中學，着重多元發展。", student_count: 840, parent_rating: 4.4 },
  // PRIMARY SCHOOLS
  { name: "聖公會明基小學", name_en: "SKH Ming Kei College Primary School", address: "中西區衛城道7號", phone: "2540 7781", district: "中西區", level: "小學", type: "資助", gender: "男女", established: 2000, teaching_lang: "中文", features: ["英語戲劇","STEM","合唱","田徑"], description: "中西區優質聖公會小學，着重英語及學術均衡發展。", student_count: 620, parent_rating: 4.5 },
  { name: "合一堂學校", name_en: "Yeshurun College", address: "中西區般咸道9號", phone: "2546 2181", district: "中西區", level: "小學", type: "資助", gender: "男女", established: 1953, teaching_lang: "中文", features: ["音樂","體育","美術"], description: "中西區著名官津小學，功課壓力適中，校風良好。", student_count: 550, parent_rating: 4.4 },
  { name: "軒尼詩道官立小學", name_en: "Hennessy Road Government Primary School", address: "灣仔軒尼詩道230號", phone: "2572 2668", district: "灣仔", level: "小學", type: "官立", gender: "男女", established: 1949, teaching_lang: "中文", features: ["田徑","游泳","足球","舞蹈"], description: "灣仔區著名官立小學，資助學額充足。", student_count: 720, parent_rating: 4.5 },
  { name: "瑪利曼小學", name_en: "Marymount Primary School", address: "灣仔跑馬地藍塘道61號", phone: "2575 2918", district: "灣仔", level: "小學", type: "資助", gender: "女", established: 1936, teaching_lang: "英文", features: ["音樂","舞蹈","田徑","網球","戲劇"], description: "灣仔區著名英文女小學，一條龍升讀瑪利曼中學。", student_count: 640, parent_rating: 4.7 },
  { name: "皇仁書院附屬小學", name_en: "Queen's College Primary School", address: "灣仔肇輝臺1號", phone: "2571 8678", district: "灣仔", level: "小學", type: "官立", gender: "男", established: 1914, teaching_lang: "英文", features: ["足球","田徑","合唱","STEM"], description: "皇仁書院附屬小學，一條龍升讀皇仁書院。", student_count: 520, parent_rating: 4.6 },
  { name: "聖若瑟小學", name_en: "St. Joseph's Primary School", address: "灣仔堅尼地道46號", phone: "2522 3844", district: "灣仔", level: "小學", type: "資助", gender: "男", established: 1872, teaching_lang: "中文", features: ["足球","田徑","合唱"], description: "灣仔區歷史悠久男校，校風純樸。", student_count: 580, parent_rating: 4.3 },
  { name: "寶血小學", name_en: "Precious Blood Primary School", address: "灣仔跑馬地雲地利道17號", phone: "2575 2971", district: "灣仔", level: "小學", type: "資助", gender: "女", established: 1936, teaching_lang: "中文", features: ["音樂","舞蹈","田徑"], description: "跑馬地區著名女校，校風純樸。", student_count: 600, parent_rating: 4.4 },
  { name: "北角衞理小學", name_en: "North Point Methodist Primary School", address: "北角渣華道82號", phone: "2566 2271", district: "東區", level: "小學", type: "資助", gender: "男女", established: 1962, teaching_lang: "中文", features: ["田徑","足球","合唱"], description: "北角區著名 Happy School，功課量適中，校風良好。", student_count: 640, parent_rating: 4.6 },
  { name: "北角官立小學", name_en: "North Point Government Primary School", address: "北角書局街26號", phone: "2563 0171", district: "東區", level: "小學", type: "官立", gender: "男女", established: 1947, teaching_lang: "中文", features: ["游泳","田徑","足球"], description: "北角區老牌官小，着重學術基礎訓練。", student_count: 700, parent_rating: 4.4 },
  { name: "聖公會聖米迦勒小學", name_en: "SKH St. Michael's Primary School", address: "北角屈臣道15號", phone: "2562 0271", district: "東區", level: "小學", type: "資助", gender: "男女", established: 1962, teaching_lang: "中文", features: ["足球","田徑","合唱","STEM"], description: "北角區聖公會優質小學，着重紀律及學術均衡發展。", student_count: 660, parent_rating: 4.5 },
  { name: "筲箕灣官立小學", name_en: "Shau Kei Wan Government Primary School", address: "筲箕灣道160號", phone: "2568 0171", district: "東區", level: "小學", type: "官立", gender: "男女", established: 1960, teaching_lang: "中文", features: ["足球","田徑","游泳"], description: "筲箕灣區老牌官小，學額充足，校風純樸。", student_count: 680, parent_rating: 4.2 },
  { name: "愛秩序灣官立小學", name_en: "Aldrich Bay Government Primary School", address: "愛秩序灣愛信道20號", phone: "2562 8171", district: "東區", level: "小學", type: "官立", gender: "男女", established: 1996, teaching_lang: "中文", features: ["游泳","田徑","舞蹈","STEM"], description: "愛秩序灣區新型官小，教學設備完善。", student_count: 720, parent_rating: 4.4 },
  { name: "香港中國婦女會學校", name_en: "Hong Kong Chinese Women's Club School", address: "西灣河�景路28號", phone: "2568 0271", district: "東區", level: "小學", type: "資助", gender: "男女", established: 1965, teaching_lang: "中文", features: ["田徑","游泳","舞蹈","合唱"], description: "西灣河區著名學校，着重兩文三語，全面發展。", student_count: 740, parent_rating: 4.5 },
  { name: "聖公會置富始南小學", name_en: "SKH Chai Wan Chi Lai Primary School", address: "置富道9號", phone: "2552 7171", district: "南區", level: "小學", type: "資助", gender: "男女", established: 1967, teaching_lang: "中文", features: ["足球","田徑","合唱","舞蹈"], description: "置富區聖公會小學，功課量適中，校風純樸。", student_count: 560, parent_rating: 4.2 },
  { name: "香島道官立小學", name_en: "Island Road Government Primary School", address: "壽臣山道21號", phone: "2552 3311", district: "南區", level: "小學", type: "官立", gender: "男女", established: 1949, teaching_lang: "中文", features: ["游泳","田徑","足球"], description: "南區老牌官小，着重學術基礎及均衡發展。", student_count: 620, parent_rating: 4.4 },
  { name: "協恩中學附屬小學", name_en: "Heep Yunn School Primary Section", address: "九龍城農圃道1號A", phone: "2382 0671", district: "九龍城", level: "小學", type: "資助", gender: "女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["田徑","游泳","舞蹈","合唱","STEM"], description: "一條龍名校附屬小學，全面發展，升中成績優異。", student_count: 720, parent_rating: 4.8 },
  { name: "英華小學", name_en: "Ying Wa Primary School", address: "九龍城天光道8號", phone: "2382 1631", district: "九龍城", level: "小學", type: "資助", gender: "男", band: "Band 1", established: 1819, teaching_lang: "英文", features: ["田徑","游泳","足球","合唱","STEM"], description: "一條龍名校附屬小學，全面發展，升中成績冠絕全港。", student_count: 780, parent_rating: 4.9 },
  { name: "九龍塘學校 (小學部)", name_en: "Kowloon Tong School (Primary Section)", address: "九龍城範園道12號", phone: "2383 0351", district: "九龍城", level: "小學", type: "資助", gender: "男女", band: "Band 1", established: 1936, teaching_lang: "英文", features: ["田徑","游泳","合唱","戲劇","舞蹈"], description: "著名一條龍小學，兩文三語教學，升中派位成績優異。", student_count: 760, parent_rating: 4.8 },
  { name: "香港培正中學附屬小學", name_en: "Pui Ching Primary School", address: "九龍城延文禮士道33號", phone: "2382 0881", district: "九龍城", level: "小學", type: "資助", gender: "男女", band: "Band 1", established: 1933, teaching_lang: "中文", features: ["田徑","游泳","合唱","足球","STEM"], description: "一條龍名校附屬小學，全面發展，升中派位成績優異。", student_count: 740, parent_rating: 4.7 },
  { name: "民生書院小學", name_en: "Munsang College Primary School", address: "九龍城京士柏道31號", phone: "2382 1781", district: "九龍城", level: "小學", type: "直資", gender: "男女", established: 1926, teaching_lang: "中文", features: ["田徑","游泳","合唱","舞蹈","STEM"], description: "著名一條龍小學，全面發展，升中派位成績理想。", student_count: 720, parent_rating: 4.5 },
  { name: "喇沙小學", name_en: "La Salle Primary School", address: "九龍城嘉林邊道31號", phone: "2382 0331", district: "九龍城", level: "小學", type: "資助", gender: "男", band: "Band 1", established: 1932, teaching_lang: "英文", features: ["足球","籃球","游泳","田徑","合唱"], description: "一條龍喇沙書院附屬小學，九龍城區頂級男小。", student_count: 780, parent_rating: 4.8 },
  { name: "黃埔宣道小學", name_en: "Alliance Primary School Whampoa", address: "紅磡黃埔花園德定街21號", phone: "2363 0371", district: "九龍城", level: "小學", type: "資助", gender: "男女", established: 1960, teaching_lang: "中文", features: ["田徑","足球","合唱","舞蹈"], description: "紅磡區著名津小，校風良好，功課量適中。", student_count: 660, parent_rating: 4.4 },
  { name: "聖公會聖十架小學", name_en: "SKH Holy Cross Primary School", address: "九龍城馬坑涌道2號", phone: "2382 1911", district: "九龍城", level: "小學", type: "資助", gender: "男女", established: 1957, teaching_lang: "中文", features: ["田徑","足球","合唱","舞蹈"], description: "九龍城區聖公會津小，着重紀律及品德培養。", student_count: 640, parent_rating: 4.3 },
  { name: "陳瑞祺學校", name_en: "Chan Sui Ki School", address: "九龍城窩打老道67號", phone: "2382 1551", district: "九龍城", level: "小學", type: "資助", gender: "男女", established: 1950, teaching_lang: "中文", features: ["田徑","合唱","舞蹈","美術"], description: "九龍城區老牌津小，着重品德及學術均衡培養。", student_count: 640, parent_rating: 4.3 },
  { name: "循道學校", name_en: "Methodist College", address: "旺角洗衣街89號", phone: "2380 0371", district: "油尖旺", level: "小學", type: "資助", gender: "男女", established: 1951, teaching_lang: "英文", features: ["田徑","游泳","合唱","舞蹈","足球"], description: "旺角區著名小學，循道衞理一條龍名校，升中派位成績優異。", student_count: 780, parent_rating: 4.6 },
  { name: "德信學校", name_en: "Tak Sun Primary School", address: "旺角窩打老道72號B", phone: "2380 0511", district: "油尖旺", level: "小學", type: "資助", gender: "男", established: 1935, teaching_lang: "中文", features: ["足球","田徑","合唱"], description: "旺角區著名男小，天主教背景，校風純樸。", student_count: 580, parent_rating: 4.4 },
  { name: "佐敦道官立小學", name_en: "Jordan Road Government Primary School", address: "佐敦道18號", phone: "2735 0171", district: "油尖旺", level: "小學", type: "官立", gender: "男女", established: 1949, teaching_lang: "中文", features: ["田徑","游泳","舞蹈","合唱"], description: "佐敦區老牌官小，資助學額充足，校風純樸。", student_count: 700, parent_rating: 4.3 },
  { name: "油麻地官立小學", name_en: "Yau Ma Tei Government Primary School", address: "油麻地北海街17號", phone: "2388 4681", district: "油尖旺", level: "小學", type: "官立", gender: "男女", established: 1947, teaching_lang: "中文", features: ["田徑","游泳","足球"], description: "油麻地區老牌官小，着重基礎學術訓練。", student_count: 680, parent_rating: 4.2 },
  { name: "大角嘴天主教小學", name_en: "Tai Kok Tsui Catholic Primary School", address: "大角嘴福利街28號", phone: "2395 0271", district: "油尖旺", level: "小學", type: "資助", gender: "男女", established: 1968, teaching_lang: "中文", features: ["田徑","舞蹈","合唱","足球"], description: "大角嘴區天主教津小，校風純樸。", student_count: 620, parent_rating: 4.3 },
  { name: "長沙灣官立小學", name_en: "Cheung Sha Wan Government Primary School", address: "長沙灣道62號", phone: "2777 0171", district: "深水埗", level: "小學", type: "官立", gender: "男女", established: 1950, teaching_lang: "中文", features: ["田徑","游泳","舞蹈","合唱"], description: "長沙灣區老牌官小，校風純樸。", student_count: 700, parent_rating: 4.2 },
  { name: "聖公會聖多馬小學", name_en: "SKH St. Thomas' Primary School", address: "深水埗道68號", phone: "2777 0271", district: "深水埗", level: "小學", type: "資助", gender: "男女", established: 1956, teaching_lang: "中文", features: ["田徑","足球","合唱","舞蹈"], description: "深水埗區聖公會津小，着重紀律及品德培養。", student_count: 620, parent_rating: 4.2 },
  { name: "沙田官立小學", name_en: "Sha Tin Government Primary School", address: "沙田大圍積福街38號", phone: "2692 0381", district: "沙田", level: "小學", type: "官立", gender: "男女", established: 1949, teaching_lang: "中文", features: ["田徑","游泳","足球","合唱"], description: "沙田區老牌官小，着重基礎學術訓練。", student_count: 720, parent_rating: 4.4 },
  { name: "聖公會主風小學", name_en: "SKH Holy Spirit Primary School", address: "馬鞍山耀安邨", phone: "2641 0281", district: "沙田", level: "小學", type: "資助", gender: "男女", established: 1990, teaching_lang: "中文", features: ["田徑","足球","合唱","舞蹈"], description: "馬鞍山區聖公會津小，功課量適中。", student_count: 640, parent_rating: 4.3 },
  { name: "保良局莊庾小學", name_en: "PLK Chong Yei Primary School", address: "沙田沙田圍路42號", phone: "2692 8382", district: "沙田", level: "小學", type: "資助", gender: "男女", established: 1970, teaching_lang: "中文", features: ["田徑","足球","合唱","舞蹈"], description: "沙田區保良局津小，功課量適中，校風純樸。", student_count: 620, parent_rating: 4.2 },
  { name: "浸會大學附屬學校王錦輝中小學 (小學)", name_en: "HKBU Affiliated School Wang Fook Primary", address: "沙田銀城街30號A", phone: "2691 6888", district: "沙田", level: "小學", type: "直資", gender: "男女", established: 2006, teaching_lang: "英文", features: ["游泳","田徑","合唱","STEM","戲劇"], description: "一條龍名校附屬小學，STEM教育見稱。", student_count: 900, parent_rating: 4.8 },
  { name: "優才書院 (小學)", name_en: "G.T. (Ellen Yeung) College Primary Section", address: "將軍澳蓬萊路3號A", phone: "2704 6888", district: "將軍澳", level: "小學", type: "直資", gender: "男女", established: 2002, teaching_lang: "英文", features: ["合唱","舞蹈","STEM","戲劇"], description: "著名一條龍小學，全面發展，着重創意教育。", student_count: 720, parent_rating: 4.7 },
];

// Insert in batches of 20
const batchSize = 20;
let success = 0;
let failed = 0;
const failedSchools = [];

for (let i = 0; i < schools.length; i += batchSize) {
  const batch = schools.slice(i, i + batchSize);
  const { data, error } = await supabase.from("schools").insert(batch);
  if (error) {
    console.error(`Batch ${i}-${i+batchSize} error:`, error.message);
    failed += batch.length;
    failedSchools.push(...batch.map(s => s.name));
  } else {
    success += batch.length;
    console.log(`Inserted ${success}/${schools.length}...`);
  }
}

console.log(`\n✅ Done! Inserted: ${success}, Failed: ${failed}`);
if (failedSchools.length) console.log("Failed schools:", failedSchools.join(", "));
