/**
 * HK Schools Database Seeder
 * Run: node scripts/seed_schools.mjs
 */

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://jypwqezctpidgiqqolaq.supabase.co";
const SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cHdxZXpjdHBpZGdpcXFvbGFxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjMzOTc5OCwiZXhwIjoyMDkxOTE1Nzk4fQ.dyC2R37zh6E4Xju8sc2mOVFPbzuaKsWA3Mjo545joj0";

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: { persistSession: false }
});

// ─── ENRICHED SCHOOLS DATA ────────────────────────────────────────────
// Every school: Chinese name, English name, address, phone, district, type,
// level, gender, funding, religion, band (secondary), school_network,
// website, features,Established year, school_size,aching language

const schools = [
  // ══════════════════════════════════════════════
  // HONG KONG ISLAND
  // ══════════════════════════════════════════════

  // ── 中西區 Central & Western ──
  {
    name: "聖保羅書院",
    name_en: "St. Paul's College",
    address: "中環麥當勞道2號",
    phone: "2529 1208",
    district: "中西區",
    district_zone: "香港島",
    level: "中學",
    school_type: "直資",
    gender: "男",
    funding: "直資",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1851,
    teaching_lang: "英文",
    features: ["音樂", "體育", "STEM", "辯論", "欖球"],
    website: "https://www.spcc.edu.hk",
    description: "香港歷史最悠久的直資男校之一，學術成績卓越，HKDSE及升學率極高。",
    student_count: 900,
    parent_rating: 4.8,
  },
  {
    name: "聖保羅男女中學附屬小學",
    name_en: "St. Paul's Co-educational College Primary Section",
    address: "南區薄扶林道144號",
    phone: "2546 2381",
    district: "南區",
    district_zone: "香港島",
    level: "小學",
    school_type: "直資",
    gender: "男女",
    funding: "直資",
    religion: "基督教",
    network: "聖公會",
    established: 1888,
    teaching_lang: "英文",
    features: ["音樂", "體育", "STEM", "舞蹈", "戲劇"],
    website: "https://www.spcc.edu.hk",
    description: "一條龍名校，直資學校，兩文三語教學，學生成績優異。",
    student_count: 1200,
    parent_rating: 4.9,
  },
  {
    name: "英皇書院",
    name_en: "King's College",
    address: "中西區荷李活道75號",
    phone: "2540 3101",
    district: "中西區",
    district_zone: "香港島",
    level: "中學",
    school_type: "官立",
    gender: "男",
    funding: "官立",
    religion: "無",
    band: "Band 1",
    established: 1862,
    teaching_lang: "英文",
    features: ["游泳", "田徑", "籃球", "STEM"],
    website: "https://www.kings.edu.hk",
    description: "歷史悠久官立男校，HKDSE成績出眾，位於中環心臟地帶。",
    student_count: 850,
    parent_rating: 4.6,
  },
  {
    name: "聖士提反堂中學",
    name_en: "St. Stephen's Girls' College",
    address: "中西區堅道26號",
    phone: "2522 5139",
    district: "中西區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1906,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "戲劇", "田徑", "網球"],
    website: "https://www.ssgc.edu.hk",
    description: "傳統名校，學術及非學術表現均出類拔萃，校友名人輩出。",
    student_count: 750,
    parent_rating: 4.7,
  },
  {
    name: "嘉諾撒聖心學校",
    name_en: "Sacred Heart Canossian School",
    address: "中西區聖母雪地殿徑1號",
    phone: "2522 3721",
    district: "中西區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    network: "嘉諾撒仁愛女修會",
    established: 1860,
    teaching_lang: "中文",
    features: ["音樂", "舞蹈", "田徑", "美術"],
    website: "https://www.shcs.edu.hk",
    description: "百年女校，基督教兩文三語教學，校風純樸，學術成績優異。",
    student_count: 650,
    parent_rating: 4.6,
  },
  {
    name: "合一堂學校",
    name_en: "Yeshurun College",
    address: "中西區般咸道9號",
    phone: "2546 2181",
    district: "中西區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "中華基督教會",
    established: 1953,
    teaching_lang: "中文",
    features: ["音樂", "體育", "美術"],
    website: "",
    description: "中西區著名官津小學，功課壓力適中，校風良好。",
    student_count: 550,
    parent_rating: 4.4,
  },
  {
    name: "新會商會學校",
    name_en: "New Wu Mien Wu College",
    address: "中西區西環太康街21號",
    phone: "2817 2389",
    district: "中西區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "無",
    network: "新會商會",
    established: 1955,
    teaching_lang: "中文",
    features: ["游泳", "足球", "田徑"],
    website: "",
    description: "西環區家長口碑小學，着重全面發展。",
    student_count: 480,
    parent_rating: 4.3,
  },
  {
    name: "聖公會明基小學",
    name_en: "SKH Ming Kei College Primary School",
    address: "中西區衛城道7號",
    phone: "2540 7781",
    district: "中西區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "聖公會",
    established: 2000,
    teaching_lang: "中文",
    features: ["英語戲劇", "STEM", "合唱", "田徑"],
    website: "https://www.skhmkc.edu.hk",
    description: "中西區優質聖公會小學，着重英語及學術均衡發展。",
    student_count: 620,
    parent_rating: 4.5,
  },

  // ── 灣仔區 Wan Chai ──
  {
    name: "華仁書院",
    name_en: "Wah Yan College",
    address: "灣仔皇后大道東281號",
    phone: "2572 5227",
    district: "灣仔區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "耶穌會",
    established: 1919,
    teaching_lang: "英文",
    features: ["戲劇", "足球", "籃球", "辯論", "管弦樂"],
    website: "https://www.wahyan.edu.hk",
    description: "耶穌會辦學，傳統名校，着重全人教育，學術成績卓越。",
    student_count: 900,
    parent_rating: 4.8,
  },
  {
    name: "香港真光中學",
    name_en: "True Light Middle School of Hong Kong",
    address: "灣仔區跑馬地黃泥涌道51號",
    phone: "2575 5923",
    district: "灣仔區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    established: 1936,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "游泳", "美術"],
    website: "https://www.tlmshk.edu.hk",
    description: "真光旗下名牌女校，着重女性領導力培養，學術及藝術表現出眾。",
    student_count: 820,
    parent_rating: 4.7,
  },
  {
    name: "聖保祿中學",
    name_en: "St. Paul's Convent School",
    address: "灣仔區皇后大道東57號",
    phone: "2528 8131",
    district: "灣仔區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "聖保祿修會",
    established: 1854,
    teaching_lang: "英文",
    features: ["音樂", "戲劇", "田徑", "網球", "合唱"],
    website: "https://www.spcs.edu.hk",
    description: "香港歷史最悠久的女校之一，校風純樸，學術成績優異。",
    student_count: 800,
    parent_rating: 4.6,
  },
  {
    name: "軒尼詩道官立小學",
    name_en: "Hennessy Road Government Primary School",
    address: "灣仔區軒尼詩道230號",
    phone: "2572 2668",
    district: "灣仔區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "12",
    established: 1949,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "足球", "舞蹈", "美術"],
    website: "",
    description: "灣仔區著名官立小學，資助學額充足，功課量適中，校風良好。",
    student_count: 720,
    parent_rating: 4.5,
  },
  {
    name: "寶血小學",
    name_en: "Precious Blood Primary School",
    address: "灣仔區跑馬地雲地利道17號",
    phone: "2575 2971",
    district: "灣仔區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    network: "寶血女修會",
    established: 1936,
    teaching_lang: "中文",
    features: ["音樂", "舞蹈", "田徑", "美術"],
    website: "",
    description: "跑馬地區著名女校，校風純樸，着重品德教育。",
    student_count: 600,
    parent_rating: 4.4,
  },
  {
    name: "聖若瑟小學",
    name_en: "St. Joseph's Primary School",
    address: "灣仔區堅尼地道46號",
    phone: "2522 3844",
    district: "灣仔區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    network: "天主教區",
    established: 1872,
    teaching_lang: "中文",
    features: ["足球", "田徑", "合唱", "美術"],
    website: "",
    description: "灣仔區歷史悠久男校，校風純樸，着重品德培養。",
    student_count: 580,
    parent_rating: 4.3,
  },
  {
    name: "瑪利曼小學",
    name_en: "Marymount Primary School",
    address: "灣仔區跑馬地藍塘道61號",
    phone: "2575 2918",
    district: "灣仔區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    network: "瑪利曼修會",
    established: 1936,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "網球", "戲劇"],
    website: "https://www.marymount.edu.hk",
    description: "灣仔區著名英文女小學，一條龍升讀瑪利曼中學，校風國際化。",
    student_count: 640,
    parent_rating: 4.7,
  },
  {
    name: "東華三院李潤田紀念中學",
    name_en: "TWGHs Lee Ching Dea Memorial College",
    address: "灣仔區皇后大道東48號",
    phone: "2528 2171",
    district: "灣仔區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "無",
    band: "Band 2",
    network: "東華三院",
    established: 1961,
    teaching_lang: "英文",
    features: ["舞蹈", "足球", "STEM", "美術"],
    website: "",
    description: "東華三院屬校，校風純樸，着重多元發展。",
    student_count: 850,
    parent_rating: 4.2,
  },
  {
    name: "皇仁書院附屬小學",
    name_en: "Queen's College Primary School",
    address: "灣仔區肇輝臺1號",
    phone: "2571 8678",
    district: "灣仔區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "男",
    funding: "官立",
    religion: "無",
    network: "教育局",
    established: 1914,
    teaching_lang: "英文",
    features: ["足球", "田徑", "合唱", "STEM"],
    website: "",
    description: "皇仁書院附屬小學，一條龍升讀皇仁書院，男校家長首選。",
    student_count: 520,
    parent_rating: 4.6,
  },

  // ── 東區 Eastern ──
  {
    name: "庇理羅女子中學",
    name_en: "Belcher's Girls' School",
    address: "東區北角銀幕路1號",
    phone: "2561 0261",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "官立",
    gender: "女",
    funding: "官立",
    religion: "無",
    band: "Band 1",
    established: 1950,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "舞蹈", "戲劇", "管弦樂"],
    website: "https://www.belchers.edu.hk",
    description: "北角著名官立女校，學術成績出眾，升學率極高。",
    student_count: 780,
    parent_rating: 4.7,
  },
  {
    name: "庇理羅女子中學附屬小學",
    name_en: "Belcher's Girls' School Primary Section",
    address: "東區北角銀幕路1號A",
    phone: "2561 0382",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    established: 1950,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "游泳", "戲劇"],
    website: "https://www.belchers.edu.hk",
    description: "一條龍名校附屬小學，着重兩文三語，全面發展。",
    student_count: 680,
    parent_rating: 4.6,
  },
  {
    name: "聖士提反堂小學",
    name_en: "St. Stephen's Girls' Primary School",
    address: "南區壽臣山道12號",
    phone: "2552 2341",
    district: "南區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1908,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "網球", "戲劇"],
    website: "https://www.ssgc.edu.hk",
    description: "傳統名牌女小學，一條龍升讀聖士提反堂中學，着重全人教育。",
    student_count: 620,
    parent_rating: 4.8,
  },
  {
    name: "北角衞理小學",
    name_en: "North Point Methodist Primary School",
    address: "東區北角渣華道82號",
    phone: "2566 2271",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "循道衞理聯合教會",
    established: 1962,
    teaching_lang: "中文",
    features: ["田徑", "足球", "合唱", "美術"],
    website: "",
    description: "北角區著名 Happy School，功課量適中，校風良好，家長口碑佳。",
    student_count: 640,
    parent_rating: 4.6,
  },
  {
    name: "北角官立小學",
    name_en: "North Point Government Primary School",
    address: "東區北角書局街26號",
    phone: "2563 0171",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "14",
    established: 1947,
    teaching_lang: "中文",
    features: ["游泳", "田徑", "足球", "舞蹈"],
    website: "",
    description: "北角區老牌官小，着重學術基礎訓練，校風純樸。",
    student_count: 700,
    parent_rating: 4.4,
  },
  {
    name: "聖公會聖米迦勒小學",
    name_en: "SKH St. Michael's Primary School",
    address: "東區北角屈臣道15號",
    phone: "2562 0271",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "聖公會",
    established: 1962,
    teaching_lang: "中文",
    features: ["足球", "田徑", "合唱", "STEM"],
    website: "",
    description: "北角區聖公會優質小學，着重紀律及學術均衡發展。",
    student_count: 660,
    parent_rating: 4.5,
  },
  {
    name: "滬江小學",
    name_en: "Shanghai University Primary School",
    address: "東區北角清華街10號",
    phone: "2566 2272",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "無",
    established: 1960,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "舞蹈", "美術"],
    website: "",
    description: "北角區老牌小學，着重兩文三語基礎，升中派位成績理想。",
    student_count: 580,
    parent_rating: 4.3,
  },
  {
    name: "筲箕灣官立小學",
    name_en: "Shau Kei Wan Government Primary School",
    address: "東區筲箕灣道160號",
    phone: "2568 0171",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "14",
    established: 1960,
    teaching_lang: "中文",
    features: ["足球", "田徑", "游泳", "舞蹈"],
    website: "",
    description: "筲箕灣區老牌官小，學額充足，校風純樸。",
    student_count: 680,
    parent_rating: 4.2,
  },
  {
    name: "愛秩序灣官立小學",
    name_en: "Aldrich Bay Government Primary School",
    address: "東區愛秩序灣愛信道20號",
    phone: "2562 8171",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    established: 1996,
    teaching_lang: "中文",
    features: ["游泳", "田徑", "舞蹈", "STEM"],
    website: "",
    description: "愛秩序灣區新型官小，教學設備完善，功課量適中。",
    student_count: 720,
    parent_rating: 4.4,
  },
  {
    name: "香港中國婦女會學校",
    name_en: "Hong Kong Chinese Women's Club School",
    address: "東區西灣河�景路28號",
    phone: "2568 0271",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "無",
    network: "香港中國婦女會",
    established: 1965,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "舞蹈", "合唱"],
    website: "",
    description: "西灣河區著名學校，着重兩文三語，校風純樸全面發展。",
    student_count: 740,
    parent_rating: 4.5,
  },
  {
    name: "金文泰中學",
    name_en: "Clementi Secondary School",
    address: "東區北角炮台山道30號",
    phone: "2577 8171",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "官立",
    gender: "男",
    funding: "官立",
    religion: "無",
    band: "Band 1",
    established: 1926,
    teaching_lang: "英文",
    features: ["足球", "田徑", "游泳", "籃球", "STEM"],
    website: "https://www.clementi.edu.hk",
    description: "香港最歷史悠久官中之一，學術成績出眾，科學研究表現突出。",
    student_count: 880,
    parent_rating: 4.6,
  },
  {
    name: "聖類斯中學",
    name_en: "St. Louis School",
    address: "東區北角雲景道20號",
    phone: "2563 0172",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "聖類斯修會",
    established: 1926,
    teaching_lang: "英文",
    features: ["足球", "田徑", "游泳", "籃球", "戲劇"],
    website: "https://www.supl.edu.hk",
    description: "北角著名男校，天主教背景，校風純樸，學術及體育兼備。",
    student_count: 850,
    parent_rating: 4.5,
  },
  {
    name: "張祝珊英文中學",
    name_en: "Cheung Chuk Shan College",
    address: "東區北角琴紡街1號",
    phone: "2568 0661",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    established: 1965,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "舞蹈", "合唱", "STEM"],
    website: "https://www.ccsc.edu.hk",
    description: "張祝珊家族辦學，英語教學，着重全人教育，校風良好。",
    student_count: 780,
    parent_rating: 4.6,
  },
  {
    name: "瑪利曼中學",
    name_en: "Marymount Secondary School",
    address: "東區北角藍塘道61號A",
    phone: "2575 2918",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "瑪利曼修會",
    established: 1936,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "網球", "游泳", "戲劇"],
    website: "https://www.marymount.edu.hk",
    description: "傳統名牌女校，一條龍升學，瑪利曼小學→瑪利曼中學，着重女性領袖培養。",
    student_count: 750,
    parent_rating: 4.8,
  },
  {
    name: "嘉諾撒聖方濟各書院",
    name_en: "St. Francis' Canossian College",
    address: "東區北角柏麗大道2號",
    phone: "2566 2771",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "嘉諾撒仁愛女修會",
    established: 1860,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "網球", "戲劇"],
    website: "https://www.sfcc.edu.hk",
    description: "嘉諾撒旗下頂級女校，學術及藝術表現傑出，校風純樸。",
    student_count: 720,
    parent_rating: 4.7,
  },
  {
    name: "衛理中學",
    name_en: "Methodist College",
    address: "東區北角炮台山道31號",
    phone: "2577 0261",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "循道衞理聯合教會",
    established: 1937,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "戲劇", "足球"],
    website: "https://www.mchk.edu.hk",
    description: "循道衞理著名中學，一條龍小學+中學，兩文三語着重全人教育。",
    student_count: 900,
    parent_rating: 4.6,
  },
  {
    name: "聖公會鄧肇堅中學",
    name_en: "SKH Tang Shiu Kin Secondary School",
    address: "東區北角電氣道218號",
    phone: "2562 0771",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 2",
    network: "聖公會",
    established: 1967,
    teaching_lang: "英文",
    features: ["足球", "田徑", "舞蹈", "STEM", "合唱"],
    website: "",
    description: "聖公會屬校，着重多元智能發展，校風純樸，體育表現突出。",
    student_count: 880,
    parent_rating: 4.4,
  },
  {
    name: "中華基金中學",
    name_en: "China基金 Secondary School",
    address: "東區柴灣怡盛街11號",
    phone: "2555 7661",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 2",
    established: 1956,
    teaching_lang: "英文",
    features: ["足球", "田徑", "合唱", "STEM", "美術"],
    website: "",
    description: "柴灣區老牌中學，着重基督教全人教育，校風純樸。",
    student_count: 820,
    parent_rating: 4.3,
  },
  {
    name: "文娜小學",
    name_en: "Manila Chinese Primary School",
    address: "東區柴灣小西灣道10號",
    phone: "2555 6371",
    district: "東區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    established: 1962,
    teaching_lang: "中文",
    features: ["足球", "田徑", "舞蹈", "合唱"],
    website: "",
    description: "小西灣區津貼小學，着重學術基礎及品德培養。",
    student_count: 580,
    parent_rating: 4.1,
  },
  {
    name: "香港庇理羅士女子中學",
    name_en: "Belcher's Girls' School",
    address: "東區北角銀幕路1號",
    phone: "2561 0261",
    district: "東區",
    district_zone: "香港島",
    level: "中學",
    school_type: "官立",
    gender: "女",
    funding: "官立",
    religion: "無",
    band: "Band 1",
    established: 1950,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "舞蹈", "戲劇", "管弦樂"],
    website: "https://www.belchers.edu.hk",
    description: "北角著名官立女校，兩文三語教學，學術成績出眾。",
    student_count: 780,
    parent_rating: 4.7,
  },

  // ── 南區 Southern ──
  {
    name: "聖士提反書院",
    name_en: "St. Stephen's College",
    address: "南區大潭紅山道18號",
    phone: "2552 2341",
    district: "南區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1903,
    teaching_lang: "英文",
    features: ["游泳", "帆船", "足球", "戲劇", "合唱"],
    website: "https://www.sshk.edu.hk",
    description: "南區頂級男校，逾120年歷史，全寄宿學校，校園環境優美。",
    student_count: 750,
    parent_rating: 4.8,
  },
  {
    name: "香港仔工業學校",
    name_en: "Aberdeen Technical School",
    address: "南區香港仔水塘道15號",
    phone: "2552 4121",
    district: "南區",
    district_zone: "香港島",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    band: "Band 2",
    established: 1935,
    teaching_lang: "英文",
    features: ["足球", "田徑", "機械工程", "資訊科技"],
    website: "",
    description: "南區老牌工業中學，着重技能培訓，實用為本。",
    student_count: 700,
    parent_rating: 4.0,
  },
  {
    name: "聖公會置富始南小學",
    name_en: "SKH Chai Wan Chi Lai Primary School",
    address: "南區置富道9號",
    phone: "2552 7171",
    district: "南區",
    district_zone: "香港島",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "聖公會",
    established: 1967,
    teaching_lang: "中文",
    features: ["足球", "田徑", "合唱", "舞蹈"],
    website: "",
    description: "置富區聖公會小學，功課量適中，校風純樸。",
    student_count: 560,
    parent_rating: 4.2,
  },
  {
    name: "香島道官立小學",
    name_en: "Island Road Government Primary School",
    address: "南區壽臣山道21號",
    phone: "2552 3311",
    district: "南區",
    district_zone: "香港島",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    established: 1949,
    teaching_lang: "中文",
    features: ["游泳", "田徑", "足球", "舞蹈"],
    website: "",
    description: "南區老牌官小，着重學術基礎及均衡發展。",
    student_count: 620,
    parent_rating: 4.4,
  },
  {
    name: "蒙特梭利國際學校 (香港仔)",
    name_en: "International Montessori School Aberdeen",
    address: "南區香港仔黃竹坑道61號",
    phone: "2552 8800",
    district: "南區",
    district_zone: "香港島",
    level: "小學",
    school_type: "私立",
    gender: "男女",
    funding: "私立",
    religion: "無",
    established: 2002,
    teaching_lang: "英文",
    features: ["蒙特梭利教學", "雙語", "探究學習", "美術"],
    website: "https://www.ims.edu.hk",
    description: "南區蒙特梭利國際學校，小班教學，着重自主學習。",
    student_count: 320,
    parent_rating: 4.5,
  },

  // ══════════════════════════════════════════════
  // KOWLOON
  // ══════════════════════════════════════════════

  // ── 九龍城區 Kowloon City ──
  {
    name: "喇沙書院",
    name_en: "La Salle College",
    address: "九龍城區喇沙書院道2號",
    phone: "2382 0591",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "喇沙會",
    established: 1932,
    teaching_lang: "英文",
    features: ["足球", "籃球", "游泳", "田徑", "合唱", "辯論", "STEM"],
    website: "https://www.lasalle.edu.hk",
    description: "九龍城區頂級男校，HKDSE成績冠絕全港，着重全人教育。",
    student_count: 1000,
    parent_rating: 4.9,
  },
  {
    name: "拔萃女書院",
    name_en: "Diocesan Girls' School",
    address: "九龍城區亞皆老街131號",
    phone: "2382 0171",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1860,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "游泳", "網球", "合唱", "戲劇"],
    website: "https://www.dgs.edu.hk",
    description: "香港最頂尖女校，學術及藝術表現冠絕全港，一條龍升讀附屬小學。",
    student_count: 850,
    parent_rating: 4.9,
  },
  {
    name: "拔萃女書院附屬小學",
    name_en: "Diocesan Girls' School Primary Section",
    address: "九龍城區馬莎道2號",
    phone: "2382 1871",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1860,
    teaching_lang: "英文",
    features: ["音樂", "舞蹈", "田徑", "游泳", "網球", "合唱", "戲劇"],
    website: "https://www.dgs.edu.hk",
    description: "一條龍名校附屬小學，兩文三語教學，全面發展。",
    student_count: 780,
    parent_rating: 4.9,
  },
  {
    name: "協恩中學",
    name_en: "Heep Yunn School",
    address: "九龍城區農圃道1號",
    phone: "2382 0211",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "中華基督教會",
    established: 1936,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "舞蹈", "合唱", "網球", "戲劇", "STEM"],
    website: "https://www.heepyunn.edu.hk",
    description: "九龍城區頂級女校，一條龍中學，學術及體育表現出眾。",
    student_count: 820,
    parent_rating: 4.8,
  },
  {
    name: "協恩中學附屬小學",
    name_en: "Heep Yunn School Primary Section",
    address: "九龍城區農圃道1號A",
    phone: "2382 0671",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "中華基督教會",
    established: 1936,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "舞蹈", "合唱", "網球", "STEM"],
    website: "https://www.heepyunn.edu.hk",
    description: "一條龍名校附屬小學，全面發展，升中成績優異。",
    student_count: 720,
    parent_rating: 4.8,
  },
  {
    name: "英華書院",
    name_en: "Ying Wa College",
    address: "九龍城區窩打老道75號",
    phone: "2383 0031",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "中華基督教會",
    established: 1819,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "足球", "合唱", "辯論", "STEM"],
    website: "https://www.yingwa.edu.hk",
    description: "全港歷史最悠久的中學之一，九龍城區頂級男校，着重全人教育。",
    student_count: 900,
    parent_rating: 4.8,
  },
  {
    name: "英華小學",
    name_en: "Ying Wa Primary School",
    address: "九龍城區天光道8號",
    phone: "2382 1631",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "中華基督教會",
    established: 1819,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "足球", "合唱", "辯論", "STEM"],
    website: "https://www.yingwa.edu.hk",
    description: "一條龍名校附屬小學，全面發展，升中成績冠絕全港。",
    student_count: 780,
    parent_rating: 4.9,
  },
  {
    name: "瑪利諾書院",
    name_en: "Maryknoll Secondary School",
    address: "九龍城區窩打老道72號",
    phone: "2383 0101",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "瑪利諾會",
    established: 1921,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "戲劇", "舞蹈", "STEM"],
    website: "https://www.mss.edu.hk",
    description: "九龍城區頂級女校，天主教背景，學術及藝術表現出眾。",
    student_count: 800,
    parent_rating: 4.7,
  },
  {
    name: "拔萃男書院",
    name_en: "Diocesan Boys' School",
    address: "九龍城區京士柏道61號",
    phone: "2382 0611",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "直資",
    gender: "男",
    funding: "直資",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1869,
    teaching_lang: "英文",
    features: ["游泳", "足球", "田徑", "籃球", "合唱", "辯論", "戲劇", "STEM"],
    website: "https://www.dbs.edu.hk",
    description: "全港最頂尖直資男校，學術及體育表現冠絕，音樂及合唱享譽國際。",
    student_count: 1100,
    parent_rating: 4.9,
  },
  {
    name: "華仁書院 (九龍)",
    name_en: "Wah Yan College, Kowloon",
    address: "九龍城區窩打老道54號",
    phone: "2382 0101",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "耶穌會",
    established: 1924,
    teaching_lang: "英文",
    features: ["足球", "籃球", "田徑", "合唱", "辯論", "戲劇"],
    website: "https://www.wyk.edu.hk",
    description: "耶穌會辦學，九龍城區頂級男校，全人教育着重心靈培育。",
    student_count: 880,
    parent_rating: 4.7,
  },
  {
    name: "真光女書院",
    name_en: "True Light Girls' College",
    address: "九龍城區窩打老道76號",
    phone: "2761 5491",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    established: 1936,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "舞蹈", "合唱", "戲劇"],
    website: "https://www.tlgc.edu.hk",
    description: "九龍城區著名女校，真光旗下名牌，着重女性領袖培養。",
    student_count: 780,
    parent_rating: 4.6,
  },
  {
    name: "迦密中學",
    name_en: "Carmel Secondary School",
    address: "九龍城區窩打老道81號",
    phone: "2761 5481",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "中華基督教會",
    established: 1939,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "足球", "戲劇", "STEM"],
    website: "https://www.carmel.edu.hk",
    description: "九龍城區著名中學，基督教背景，學術及體育均衡發展。",
    student_count: 860,
    parent_rating: 4.6,
  },
  {
    name: "九龍塘學校 (中學部)",
    name_en: "Kowloon Tong School (Secondary Section)",
    address: "九龍城區窩打老道72號A",
    phone: "2383 0331",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "九龍塘學校",
    established: 1936,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "戲劇", "舞蹈"],
    website: "",
    description: "九龍塘學校一條龍中學部，著名升學名校，着重學術成績。",
    student_count: 800,
    parent_rating: 4.7,
  },
  {
    name: "九龍塘學校 (小學部)",
    name_en: "Kowloon Tong School (Primary Section)",
    address: "九龍城區範園道12號",
    phone: "2383 0351",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "九龍塘學校",
    established: 1936,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "戲劇", "舞蹈"],
    website: "",
    description: "著名一條龍小學，兩文三語教學，全面發展，升中派位成績優異。",
    student_count: 760,
    parent_rating: 4.8,
  },
  {
    name: "香港培正中學",
    name_en: "Pui Ching Middle School",
    address: "九龍城區窩打老道71號",
    phone: "2761 5471",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    established: 1933,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "足球", "辯論", "STEM"],
    website: "https://www.puiching.edu.hk",
    description: "九龍城區著名中學，基督教背景，學術及體育傳統名校。",
    student_count: 880,
    parent_rating: 4.7,
  },
  {
    name: "香港培正中學附屬小學",
    name_en: "Pui Ching Primary School",
    address: "九龍城區延文禮士道33號",
    phone: "2382 0881",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "香港培正中學",
    established: 1933,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "合唱", "足球", "STEM"],
    website: "https://www.puiching.edu.hk",
    description: "一條龍名校附屬小學，全面發展，升中派位成績優異。",
    student_count: 740,
    parent_rating: 4.7,
  },
  {
    name: "聖公會聖三一堂中學",
    name_en: "SKH Holy Trinity Cathedral College",
    address: "九龍城區嘉林邊道21號",
    phone: "2382 1701",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "聖公會",
    established: 1956,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "舞蹈", "足球"],
    website: "",
    description: "九龍城區聖公會中學，學術及非學術均衡發展。",
    student_count: 820,
    parent_rating: 4.5,
  },
  {
    name: "東華三院黃笏南中學",
    name_en: "TWGHs Wong Fuk Hwa College",
    address: "九龍城區馬坑涌道18號",
    phone: "2382 1611",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "無",
    band: "Band 2",
    network: "東華三院",
    established: 1961,
    teaching_lang: "英文",
    features: ["足球", "田徑", "舞蹈", "STEM"],
    website: "",
    description: "東華三院屬校，着重多元智能發展。",
    student_count: 840,
    parent_rating: 4.3,
  },
  {
    name: "民生書院",
    name_en: "Munsang College",
    address: "九龍城區馬莎道16號",
    phone: "2382 1771",
    district: "九龍城區",
    district_zone: "九龍",
    level: "中學",
    school_type: "直資",
    gender: "男女",
    funding: "直資",
    religion: "基督教",
    band: "Band 2",
    established: 1926,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "戲劇", "STEM"],
    website: "https://www.munsang.edu.hk",
    description: "九龍城區老牌直資中學，一條龍小學+中學，着重全人教育。",
    student_count: 900,
    parent_rating: 4.5,
  },
  {
    name: "民生書院小學",
    name_en: "Munsang College Primary School",
    address: "九龍城區京士柏道31號",
    phone: "2382 1781",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "直資",
    gender: "男女",
    funding: "直資",
    religion: "基督教",
    network: "民生書院",
    established: 1926,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "合唱", "舞蹈", "STEM"],
    website: "https://www.munsang.edu.hk",
    description: "著名一條龍小學，全面發展，升中派位成績理想。",
    student_count: 720,
    parent_rating: 4.5,
  },
  {
    name: "喇沙小學",
    name_en: "La Salle Primary School",
    address: "九龍城區嘉林邊道31號",
    phone: "2382 0331",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    band: "Band 1",
    network: "喇沙會",
    established: 1932,
    teaching_lang: "英文",
    features: ["足球", "籃球", "游泳", "田徑", "合唱", "辯論"],
    website: "https://www.lasalle.edu.hk",
    description: "一條龍喇沙書院附屬小學，九龍城區頂級男小，學術及體育兼備。",
    student_count: 780,
    parent_rating: 4.8,
  },
  {
    name: "陳瑞祺學校",
    name_en: "Chan Sui Ki School",
    address: "九龍城區窩打老道67號",
    phone: "2382 1551",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "中華基督教會",
    established: 1950,
    teaching_lang: "中文",
    features: ["田徑", "合唱", "舞蹈", "美術"],
    website: "",
    description: "九龍城區老牌津小，着重品德及學術均衡培養。",
    student_count: 640,
    parent_rating: 4.3,
  },
  {
    name: "合一堂學校",
    name_en: "Yeshurun College",
    address: "九龍城區伯爵街15號",
    phone: "2383 0711",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "中華基督教會",
    established: 1953,
    teaching_lang: "中文",
    features: ["田徑", "足球", "合唱", "舞蹈"],
    website: "",
    description: "九龍城區基督教津小，校風純樸，功課量適中。",
    student_count: 620,
    parent_rating: 4.3,
  },
  {
    name: "黃埔宣道小學",
    name_en: "Alliance Primary School Whampoa",
    address: "九龍城區紅磡黃埔花園德定街21號",
    phone: "2363 0371",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "宣道會",
    established: 1960,
    teaching_lang: "中文",
    features: ["田徑", "足球", "合唱", "舞蹈"],
    website: "",
    description: "紅磡區著名津小，宣道會背景，校風良好，功課量適中。",
    student_count: 660,
    parent_rating: 4.4,
  },
  {
    name: "聖公會聖十架小學",
    name_en: "SKH Holy Cross Primary School",
    address: "九龍城區馬坑涌道2號",
    phone: "2382 1911",
    district: "九龍城區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "聖公會",
    established: 1957,
    teaching_lang: "中文",
    features: ["田徑", "足球", "合唱", "舞蹈"],
    website: "",
    description: "九龍城區聖公會津小，着重紀律及品德培養。",
    student_count: 640,
    parent_rating: 4.3,
  },

  // ── 油尖旺區 Yau Tsim Mong ──

  {
    name: "循道學校",
    name_en: "Methodist College",
    address: "油尖旺區旺角洗衣街89號",
    phone: "2380 0371",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "循道衞理聯合教會",
    established: 1951,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "舞蹈", "足球"],
    website: "https://www.mchk.edu.hk",
    description: "旺角區著名小學，循道衞理一條龍名校，升中派位成績優異。",
    student_count: 780,
    parent_rating: 4.6,
  },
  {
    name: "德信學校",
    name_en: "Tak Sun Primary School",
    address: "油尖旺區旺角窩打老道72號B",
    phone: "2380 0511",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "天主教",
    established: 1935,
    teaching_lang: "中文",
    features: ["足球", "田徑", "合唱", "田徑"],
    website: "",
    description: "旺角區著名男小，天主教背景，校風純樸，着重品德培養。",
    student_count: 580,
    parent_rating: 4.4,
  },
  {
    name: "佐敦道官立小學",
    name_en: "Jordan Road Government Primary School",
    address: "油尖旺區佐敦道18號",
    phone: "2735 0171",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "31",
    established: 1949,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "舞蹈", "合唱"],
    website: "",
    description: "佐敦區老牌官小，資助學額充足，校風純樸。",
    student_count: 700,
    parent_rating: 4.3,
  },
  {
    name: "油麻地官立小學",
    name_en: "Yau Ma Tei Government Primary School",
    address: "油尖旺區油麻地北海街17號",
    phone: "2388 4681",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "31",
    established: 1947,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "足球", "舞蹈"],
    website: "",
    description: "油麻地區老牌官小，着重基礎學術訓練。",
    student_count: 680,
    parent_rating: 4.2,
  },
  {
    name: "大角嘴天主教小學",
    name_en: "Tai Kok Tsui Catholic Primary School",
    address: "油尖旺區大角嘴福利街28號",
    phone: "2395 0271",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "天主教",
    established: 1968,
    teaching_lang: "中文",
    features: ["田徑", "舞蹈", "合唱", "足球"],
    website: "",
    description: "大角嘴區天主教津小，校風純樸，功課量適中。",
    student_count: 620,
    parent_rating: 4.3,
  },
  {
    name: "循道中學",
    name_en: "Methodist College",
    address: "油尖旺區旺角洗衣街89號A",
    phone: "2380 0321",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    band: "Band 1",
    network: "循道衞理聯合教會",
    established: 1951,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "舞蹈", "足球", "戲劇"],
    website: "https://www.mchk.edu.hk",
    description: "循道衞理一條龍中學，小學+中學全面發展，學術成績優異。",
    student_count: 900,
    parent_rating: 4.7,
  },
  {
    name: "九龍工業學校",
    name_en: "Kowloon Technical School",
    address: "油尖旺區旺角洗衣街151號",
    phone: "2380 0551",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "中學",
    school_type: "資助",
    gender: "男",
    funding: "資助",
    religion: "基督教",
    band: "Band 2",
    established: 1930,
    teaching_lang: "英文",
    features: ["足球", "田徑", "籃球", "機械工程"],
    website: "",
    description: "旺角區老牌工業中學，着重技能培訓及學術均衡。",
    student_count: 780,
    parent_rating: 4.1,
  },
  {
    name: "官立嘉道理爵士中學",
    name_en: "Sir Ellis Kadoorie College",
    address: "油尖旺區旺角山東街51號",
    phone: "2380 0721",
    district: "油尖旺區",
    district_zone: "九龍",
    level: "中學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    band: "Band 1",
    established: 1907,
    teaching_lang: "英文",
    features: ["田徑", "游泳", "合唱", "辯論", "足球"],
    website: "https://www.sek.edu.hk",
    description: "百年官校，全港首間官立英文中學，學術及音樂傳統出名。",
    student_count: 860,
    parent_rating: 4.6,
  },

  // ── 深水埗區 Sham Shui Po ──

  {
    name: "長沙灣官立小學",
    name_en: "Cheung Sha Wan Government Primary School",
    address: "深水埗區長沙灣道62號",
    phone: "2777 0171",
    district: "深水埗區",
    district_zone: "九龍",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "40",
    established: 1950,
    teaching_lang: "中文",
    features: ["田徑", "游泳", "舞蹈", "合唱"],
    website: "",
    description: "長沙灣區老牌官小，資助學額充足，校風純樸。",
    student_count: 700,
    parent_rating: 4.2,
  },
  {
    name: "聖公會聖多馬小學",
    name_en: "SKH St. Thomas' Primary School",
    address: "深水埗區深水埗道68號",
    phone: "2777 0271",
    district: "深水埗區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "基督教",
    network: "聖公會",
    established: 1956,
    teaching_lang: "中文",
    features: ["田徑", "足球", "合唱", "舞蹈"],
    website: "",
    description: "深水埗區聖公會津小，着重紀律及品德培養。",
    student_count: 620,
    parent_rating: 4.2,
  },
  {
    name: "寶血會智能學校",
    name_en: "Precious Blood Primary School",
    address: "深水埗區荔枝角道135號",
    phone: "2777 0371",
    district: "深水埗區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "女",
    funding: "資助",
    religion: "天主教",
    network: "寶血女修會",
    established: 1948,
    teaching_lang: "中文",
    features: ["田徑", "合唱", "舞蹈", "美術"],
    website: "",
    description: "深水埗區著名女校，天主教背景，着重品德及學術培養。",
    student_count: 580,
    parent_rating: 4.3,
  },
  {
    name: "東華三院李東海小學",
    name_en: "TWGHs Lee Tao Lee Primary School",
    address: "深水埗區石硤尾大埔道170號",
    phone: "2777 0471",
    district: "深水埗區",
    district_zone: "九龍",
    level: "小學",
    school_type: "資助",
    gender: "男女",
    funding: "資助",
    religion: "無",
    network: "東華三院",
    established: 1970,
    teaching_lang: "中文",
    features: ["田徑", "足球", "合唱", "舞蹈"],
    website: "",
    description: "石硤尾區東華三院津小，功課量適中，校風純樸。",
    student_count: 640,
    parent_rating: 4.1,
  },
  {
    name: "荔景官立小學",
    name_en: "Lai King Primary School",
    address: "深水埗區荔景山路220號",
    phone: "2744 0171",
    district: "深水埗區",
    district_zone: "九龍",
    level: "小學",
    school_type: "官立",
    gender: "男女",
    funding: "官立",
    religion: "無",
    network: "教育局",
    school_net: "40",
    established: 1961